#+SETUP_FILE: ~/org/setup2.org
#+TITLE: TV schedule API coding test
#+AUTHOR: Sean O'Halpin, BBC R&D

* Coding task description

As part of your job application, we want you to complete a coding task
to test your Javascript, CSS and HTML skills.

Your performance on this assignment will make a significant
contribution to your job application. Please use this opportunity to
show us what you can do.

Create a repository on github for your code. You must send us the
address of your github repo by 10am Friday 8 Feb 2013 and must
complete the task by 10am Monday 11 Feb 2013 at which time we will
make a copy of the repo. We will ignore any changes made to the repo
after that time.

** The task

We want you to write a single page browser application to view and
interact with a TV schedule API in JSON format provided by a node.js
server we are hosting on the internet. The application should enable a
user to view and navigate through a TV schedule and to bookmark
individual broadcasts using the REST API provided. We expect the
application to work well in modern browsers.

So, you will write a client-side application which will interact with
our REST API. We have set up our server to return the CORS headers to
allow this (so there's no need for a server at your end - you can just
provide a static HTML file and assets).

We are leaving the problem of how best to present this information up
to you. You could use a standard TV programme guide grid, for example,
or present a day at a time or enable a selection of views. The design
goal is to produce a fluid user interface that is pleasant to use that
presents the schedule information clearly. Ideally, it should work
well on desktop, tablet and mobile browsers.

Feel free to use any framework(s) you like.

** The TV schedule server

The server's address is: http://rd-broadcast-bookmarks.herokuapp.com/.

You can find the server code and documentation for the API for the
server at http://github/bbcrd/rd-broadcast-bookmarks. You can clone
this repo and run it locally to test your applications. Do not fork
this repo on github as that will reveal who you are to other
candidates.

The REST API the server provides is documented at
http://rd-broadcast-bookmarks.herokuapp.com/api (and in
docs/api.org). How to set up the server is documented in
docs/INSTALL. Note that we expect your final submitted application to
interact with our server at the url we provided above.

The schedule covers the four BBC channels and seven days worth of
data. The period covered is Saturday 26 Jan 2013 to Friday 1 Feb 2013
inclusive. The source JSON for this schedule can be found in the data
directory.

** Bookmarks

The API enables you to 'bookmark' a broadcast. We expect you to use
this interface and to represent bookmarked broadcasts in the user
interface. Note that the server we've set up does not persist these
bookmarks across reboots so you may find that previously stored
bookmarks have been cleared.

To use the bookmark API, you'll need to use a =user_id= in the API
calls. Your =user_id= should be your first initial joined to your last
name in lowercase. For example, if your name were 'John E. Smith',
your user id would be =jsmith=.

The API call to set a bookmark should look something like this:

: POST http://rd-broadcast-bookmarks.herokuapp.com/bookmarks/jsmith/p013wn96

** Questions

If you have any questions regarding the test or problems with the
server API, please contact: mailto:sean.ohalpin@bbc.co.uk
